# Generated by Django 2.2.6 on 2021-10-12 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmation_code', models.TextField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=8)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='confirmation',
            constraint=models.UniqueConstraint(fields=('email', 'confirmation_code'), name='unique_email_code'),
        ),
    ]
